"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG') == 'True'
ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves static files (Django admin CSS/JS) without a separate
    # web server — needed since there's no nginx in front on Railway.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# In production Railway injects a single DATABASE_URL; locally we fall back to
# the individual DB_* vars from .env.
if os.getenv('DATABASE_URL'):
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600),
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# collectstatic writes here; WhiteNoise serves from it in production.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# User model
AUTH_USER_MODEL = 'core.CustomUser'

# Media files (uploaded scan images). On Railway this points at a mounted
# volume so uploads survive redeploys; locally it defaults to the repo dir.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.getenv('MEDIA_ROOT', os.path.join(BASE_DIR, 'media'))

# Scan image-quality gate. These conservative defaults reject clearly unusable
# photos while allowing ordinary phone-camera variation. Override the values in
# production after calibration against real user scans.
SCAN_MIN_IMAGE_DIMENSION = int(os.getenv('SCAN_MIN_IMAGE_DIMENSION', '224'))
SCAN_BLUR_THRESHOLD = float(os.getenv('SCAN_BLUR_THRESHOLD', '25'))
SCAN_DARK_MEAN_THRESHOLD = float(os.getenv('SCAN_DARK_MEAN_THRESHOLD', '30'))
SCAN_DARK_PIXEL_RATIO = float(os.getenv('SCAN_DARK_PIXEL_RATIO', '0.80'))
SCAN_BRIGHT_MEAN_THRESHOLD = float(os.getenv('SCAN_BRIGHT_MEAN_THRESHOLD', '225'))
SCAN_BRIGHT_PIXEL_RATIO = float(os.getenv('SCAN_BRIGHT_PIXEL_RATIO', '0.85'))

# Shared binary ConvNeXt leaf/not-leaf gate. Its class-1 probability is the
# calibrated leaf score; 0.99 was selected on category-disjoint validation.
SCAN_LEAF_GATE_THRESHOLD = float(os.getenv('SCAN_LEAF_GATE_THRESHOLD', '0.99'))
SCAN_LEAF_GATE_MODEL_PATH = os.getenv(
    'SCAN_LEAF_GATE_MODEL_PATH',
    os.path.join(BASE_DIR, 'ml', 'convnext_tiny_binary_leaf_gate.pth'),
)
