# Generated by Django 6.0.5 on 2026-06-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plant_last_watered_plant_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='last_fertilized',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_misted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='days_to_harvest',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='default_fertilizer_freq_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='default_misting_freq_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='default_watering_freq_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='recommended_location',
            field=models.CharField(blank=True, choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('both', 'Indoor or outdoor')], max_length=10),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='sunlight',
            field=models.CharField(blank=True, choices=[('full_sun', 'Full sun'), ('partial_sun', 'Partial sun'), ('partial_shade', 'Partial shade'), ('shade', 'Shade')], max_length=20),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='temperature_max_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plantspecies',
            name='temperature_min_c',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='growing_tips',
            field=models.TextField(blank=True),
        ),
    ]
