# Generated by Django 6.0.5 on 2026-06-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_plant_last_fertilized_plant_last_misted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_care_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='longest_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
