# Generated by Django 6.0.5 on 2026-06-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_achievement_customuser_level_customuser_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='cause',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='prevention',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=8),
        ),
        migrations.AddField(
            model_name='disease',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='disease',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.TextField(blank=True),
        ),
    ]
