# Generated by Django 6.0.5 on 2026-06-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_disease_cause_disease_description_disease_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
