# Generated by Django 6.0.5 on 2026-06-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_community_post_comment_communitymembership_follow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carelog',
            name='activity',
            field=models.CharField(choices=[('water', 'Watered'), ('fertilize', 'Fertilized'), ('mist', 'Misted'), ('note', 'Note')], max_length=12),
        ),
    ]
