# Generated by Django 6.0.5 on 2026-06-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_carelog_note_alter_carelog_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
