# Generated by Django 6.0.5 on 2026-06-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_carelog_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='title',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
