# Generated by Django 6.0.5 on 2026-07-02 10:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_carelog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='streak_freezes',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.CreateModel(
            name='WeeklyChallengeProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('challenge_code', models.CharField(max_length=40)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_completions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
