# Generated by Django 6.0.5 on 2026-07-02 14:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customuser_streak_freezes_weeklychallengeprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('creature_skin', 'Creature skin')], default='creature_skin', max_length=20)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic')], default='common', max_length=8)),
                ('cost_seeds', models.PositiveIntegerField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('sort', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'cost_seeds', 'code'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='seeds',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.CreateModel(
            name='UserCosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipped', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cosmetic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='core.cosmetic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cosmetics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acquired_at'],
                'unique_together': {('user', 'cosmetic')},
            },
        ),
    ]
