# Generated by Django 6.0.5 on 2026-07-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmetic',
            name='kind',
            field=models.CharField(choices=[('creature_skin', 'Creature skin'), ('pot_style', 'Pot style'), ('namecard', 'Namecard')], default='creature_skin', max_length=20),
        ),
    ]
