# Generated by Django 6.0.5 on 2026-07-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_social_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantspecies',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
