# Generated by Django 6.0.5 on 2026-07-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_passwordresetcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notes/')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(limit_choices_to={'activity': 'note'}, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.carelog')),
            ],
            options={'ordering': ['position', 'id']},
        ),
    ]
