# Generated by Django 6.0.5 on 2026-07-18 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_noteimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreakFreezeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak_freeze_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('user', 'date'), name='unique_streak_freeze_usage_date')],
            },
        ),
    ]
