# Generated by Django 6.0.5 on 2026-07-19 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_streakfreezeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantspecies',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_species', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plantspecies',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
