# Generated by Django 6.0.5 on 2026-07-19 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_custom_species'),
    ]

    operations = [
        migrations.AddField(
            model_name='carelog',
            name='document',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
